


BACKUP DATABASE BD_LATAM
TO DISK= 'C:\database\BD_LATAM_FULL.BAK'
 WITH NOINIT,
 NAME='COPIA COMPLETA',
 DESCRIPTION='COPIA DIARIA'


-- EL FILELISTONLY ES PARA VER QUE ARCHIVOS SE ESTAN COPIANDO
 RESTORE FILELISTONLY
 FROM DISK= 'C:\database\BD_LATAM_FULL.BAK'
 GO

 
 RESTORE HEADERONLY
 FROM DISK= 'C:\database\BD_LATAM_FULL.BAK'
 GO



 BACKUP DATABASE BD_LATAM
 TO DISK= 'C:\database\BD_LATAM_FULL2.BAK'
    WITH INIT,
    NAME='COPIA COMPLETA',
    DESCRIPTION='COPIA DIARIA',
    STATS=10,
    FORMAT, COMPRESSION


-- EL FILELISTONLY ES PARA VER QUE ARCHIVOS SE ESTAN COPIANDO
 RESTORE FILELISTONLY
 FROM DISK= 'C:\database\BD_LATAM_FULL2.BAK'
 GO

 
 RESTORE HEADERONLY
 FROM DISK= 'C:\database\BD_LATAM_FULL2.BAK'
 GO


 -- SET LANGUAGE SPANISH


USE BD_LATAM
GO

SELECT * FROM Ciudad


--VOY A CREAR UNA TABLA UTILIZANDO LA CONSULTA SELECT NOMBRE TBLCIUDAD

SELECT * INTO TBLCIUDAD FROM Ciudad

SELECT * FROM TBLCIUDAD

-- NECESITO QUE EL ID DEL REGISTRO LIMA SE CAMBIE EL ID DE REGISTRO DE LA COLUMNA NOMBRE

UPDATE TBLCIUDAD SET NOMBRE = 'TACNA' WHERE ID=1 
UPDATE TBLCIUDAD SET NOMBRE = 'LIMA' WHERE ID=6


BACKUP DATABASE BD_LATAM
TO DISK = 'C:\database\BD_LATAM_DIFF.BAK'
    WITH DIFFERENTIAL,
    NAME='COPIA DIFERENCIAL',
    DESCRIPTION='COPIA DIFERENCIA Y DIARIA LUNEA 14PM',
    INIT
GO



/*
COPIA DE REGISTROS DE TRANSACCIONES

TIME            EVENTO
8:00 AM         COPIA SEGURIDAD DE DB
MEDIO DIA       COPIA SEGURIDAD DE TRANSACCIONES
16:00 PM        COPIA REGISTROS DE TRANSACCIONES
18:00 PM        COPIA SEGURIDAD DE DB
20:00 PM        COPIA REGISTROS DE TRANSACCIONES

*/

BACKUP LOG BD_LATAM
TO DISK = 'C:\database\BD_LATAM_LOG.BAK'
    WITH NAME = 'COPIA DEL LOG',
        DESCRIPTION='COPIA LOG. LUNEA 14PM',
        INIT


SELECT * FROM TBLCIUDAD

--ELIMAR DE LA TABLA TBLCIUDAD LA CIUDAD CHICLAYO

DELETE FROM TBLCIUDAD WHERE NOMBRE='CHICLAYO'

-- RECUPERACION DE LA BASE DE DATOS

USE MASTER
GO
RESTORE DATABASE BD_LATAM
FROM DISK = 'C:\database\BD_LATAM_FULL2.BAK'
WITH REPLACE, NORECOVERY 

RESTORE DATABASE DB_LATAM
FROM DISK = 'C:\database\BD_LATAM_DIFF.BAK'
WITH NORECOVERY

USE BD_LATAM

RESTORE LOG BD_LATAM
FROM DISK = 'C:\database\BD_LATAM_LOG.BAK'
WITH NORECOVERY
GO

RESTORE LOG BD_LATAM

USE BD_LATAM

SELECT * FROM TBLCIUDAD