
--SESION 3 _1

CREATE DATABASE VENTAS
ON(
NAME='VENTAS',
FILENAME='D:\SESION_3\VENTAS.MDF',
SIZE=4MB,
MAXSIZE=16MB,
FILEGROWTH=40%
)
LOG ON(
NAME='VENTAS_LOG',
FILENAME='D:\SESION_3\VENTAS.LDF',
SIZE=4MB,
MAXSIZE=16MB,
FILEGROWTH=3MB
)
USE VENTAS

CREATE TABLE DEPARTAMENTO(
 NRO_DEPTO NUMERIC(4) CONSTRAINT PK_DEPT PRIMARY KEY,
 NOMBRE_DEPTO  VARCHAR(20),
 LOCAL    VARCHAR(20))
go

CREATE TABLE EMPLEADO(
 NRO_EMPL     NUMERIC(4) CONSTRAINT PK_EMP PRIMARY KEY,
 NOMBRE_EMPL     VARCHAR(20),
 TRABAJO       VARCHAR(15),
 COD_TARJ       NUMERIC(4),
 FECH_CONT  DATETIME,
 SALARIO       DECIMAL(7,2),
 COMISION      DECIMAL(7,2),
 NRO_DEPTO    NUMERIC(4) )
 
 GO

 CREATE TABLE CLIENTE(
 IDCLIENTE      NUMERIC(6),
 NOMBRE       CHAR(45),
 DIRECCION     CHAR(40),
 CIUDAD       CHAR(30),
 ESTADO       CHAR(2),
 AREA        NUMERIC(3),
 TELEFONO      CHAR(9),
 REPID       NUMERIC(4),
 CREDITO_LIMITITADO NUMERIC(9,2),
 COMENTARIOS    VARCHAR(2000)
 CONSTRAINT CLIENTE_PRIMARY PRIMARY KEY(IDCLIENTE))

 go
 ALTER TABLE EMPLEADO ADD CONSTRAINT FK_DEPARTAMENTO_EMPLEADO FOREIGN KEY(NRO_DEPTO)
 REFERENCES DEPARTAMENTO(NRO_DEPTO)
 GO
 ALTER TABLE EMPLEADO ADD CONSTRAINT FK_EMPLEADO_EMPLEADO FOREIGN KEY(COD_TARJ)
 REFERENCES EMPLEADO(NRO_EMPL)

 GO
  GO
CREATE TABLE ORDEN(
 ID_ORDEN      NUMERIC(4) NOT NULL,
 FECHA_ORDEN  DATETIME,
 COMISION_PLAN   CHAR(1),
IDCLIENTE    NUMERIC(6) NOT NULL, 
 FECHA_ENVIO  DATETIME,
 TOTAL      DECIMAL(8,2) CONSTRAINT TOTAL_ZERO CHECK (TOTAL>=0),
 NRO_EMPL      NUMERIC(4)  CONSTRAINT FK_NRO_EMPL REFERENCES EMPLEADO,  
 CONSTRAINT ORDEN_FOREIGN_KEY FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
 CONSTRAINT ORDEN_PRIMARY_KEY PRIMARY KEY (ID_ORDEN))

 GO
CREATE TABLE PRODUCTO(
 IDPRODUC      NUMERIC(6) CONSTRAINT PRODUCTO_PRIMARY_KEY PRIMARY KEY,
 DESCRIPCION      CHAR(30)
 )
 
go

CREATE TABLE CATEGORIA(
 ORDCAT        NUMERIC(4) NOT NULL,
 NRO_CAT      NUMERIC(4) NOT NULL,
 IDPRODUC      NUMERIC(6),
 PRECIO_ACTUAL  DECIMAL(8,2),
 CANTIDAD     DECIMAL(8),
 TOTAL_CAT      DECIMAL(8,2),
 CONSTRAINT CATEGORIA_FOREIGN_KEY FOREIGN KEY(ORDCAT) REFERENCES ORDEN(iD_ORDEN ),
 CONSTRAINT CATEGORIA_FK_PRODUCTO FOREIGN KEY( IDPRODUC) REFERENCES PRODUCTO( IDPRODUC ),
 CONSTRAINT CATEGORIA_PRIMARY_KEY PRIMARY KEY(ORDCAT ,IDPRODUC ))
go

--REGISTROS
INSERT INTO DEPARTAMENTO VALUES(10,'CONTABILIDAD','PIURA');
INSERT INTO DEPARTAMENTO VALUES(20,'INVESTIGACION','CHICLAYO');
INSERT INTO DEPARTAMENTO VALUES(30,'VENTAS','LAMBAYEQUE');
GO
INSERT INTO EMPLEADO VALUES(7839,'WILMAN','PRESIDENTE',NULL,convert(datetime,'17/11/1981',103),5000,NULL,10);
INSERT INTO EMPLEADO VALUES(7698,'SILVER','GERENTE',7839,convert(datetime,'01/05/1981',103),2850,NULL,30);
INSERT INTO EMPLEADO VALUES(7782,'LUISA','GERENTE',7839,convert(datetime,'09/06/1981',103),2450,NULL,10);
GO
INSERT INTO PRODUCTO(IDPRODUC, DESCRIPCION) 
VALUES(100860,'RAQUETA DE TENIS ACE  I');
INSERT INTO PRODUCTO(IDPRODUC, DESCRIPCION)  
VALUES(100861,'RAQUETA DE TENIS ACE II');
INSERT INTO PRODUCTO(IDPRODUC, DESCRIPCION)  
VALUES(100862,'RAQUETA DE TENIS ACE  III');
GO
INSERT INTO CLIENTE (ESTADO  ,REPID,TELEFONO,NOMBRE ,IDCLIENTE ,CREDITO_LIMITITADO ,CIUDAD ,AREA,DIRECCION, COMENTARIOS) 
VALUES('AC',7844,'598-6609','JOCK SPORTS',100,5000,'BELMONT',415,'345 VIEWRIDGE','gente muy amable para trabajar con el representante de ventas le gusta ser llamado Mike');
INSERT INTO CLIENTE (ESTADO  ,REPID,TELEFONO,NOMBRE ,IDCLIENTE ,CREDITO_LIMITITADO ,CIUDAD ,AREA,DIRECCION, COMENTARIOS) 
VALUES('AC',7521,'368-1233','TKB SPORTS SHOP',101,'10000','REDWOOD CITY',415,'490 BOLI RD','
representante llamado 5/8 sobre cambio en orden - contac envío');


GO
USE MASTER

CREATE DATABASE RESPALDO1 ON
(NAME=[VENTAS],
FILENAME='D:\SESION_3\RESPALDO1')
AS SNAPSHOT OF [VENTAS]


USE VENTAS
SELECT * FROM DEPARTAMENTO
INSERT INTO DEPARTAMENTO VALUES(40,'OPERACIONES','TRUJILLO');
INSERT INTO DEPARTAMENTO VALUES(50,'SISTEMAS','CALLAO');


SELECT * FROM CLIENTE

UPDATE CLIENTE SET NOMBRE='JACKSPORTS' WHERE IDCLIENTE=100
UPDATE CLIENTE SET NOMBRE='SPORTS' WHERE IDCLIENTE=101

USE RESPALDO1

USE MASTER

RESTORE DATABASE [VENTAS] FROM DATABASE_SNAPSHOT='RESPALDO1'

DROP DATABASE RESPALDO1


--CREACION DE USUARIOS

CREATE LOGIN UNISISTEMAS WITH PASSWORD='654321'


------CREACION DE LA BD BIBLIOTECA-------------

CREATE DATABASE BIBLIOTECA
GO
USE BIBLIOTECA
GO
CREATE TABLE DISTRITOS
(COD_DIS CHAR(4)NOT NULL PRIMARY KEY CHECK(COD_DIS LIKE'D[0-9][0-9][0-9]'),
NOM_DIS VARCHAR(30)NOT NULL UNIQUE,
DES_DIS VARCHAR(50)NULL)
GO

CREATE TABLE TIPOS
(COD_TIP CHAR(4)NOT NULL PRIMARY KEY CHECK(COD_TIP LIKE'T[0-9][0-9][0-9]'),
NOM_TIP VARCHAR(30)NOT NULL UNIQUE,
DES_TIP VARCHAR(50)NULL)
GO
CREATE TABLE LECTORES
(COD_LEC CHAR(4)NOT NULL PRIMARY KEY CHECK(COD_LEC LIKE'L[0-9][0-9][0-9]'),
NOM_LEC VARCHAR(30)NOT NULL UNIQUE,
DIR_LEC VARCHAR(50)NOT NULL,
DIS_LEC CHAR(4)NOT NULL FOREIGN KEY(DIS_LEC)REFERENCES DISTRITOS,
TIP_LEC CHAR(4)NOT NULL FOREIGN KEY(TIP_LEC)REFERENCES TIPOS,
FRE_LEC DATETIME DEFAULT(GETDATE())NOT NULL,
EST_LEC BIT DEFAULT(1)NOT NULL,
TEL_LEC CHAR(8) NULL CHECK(TEL_LEC LIKE'[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
OBS_LEC VARCHAR(50) NULL)
GO
CREATE TABLE CARGOS
(COD_CAR CHAR(4)NOT NULL PRIMARY KEY CHECK(COD_CAR LIKE'C[0-9][0-9][0-9]'),
NOM_CAR VARCHAR(30)NOT NULL UNIQUE,
DES_CAR VARCHAR(50)NULL)
GO
CREATE TABLE PERSONAL
(COD_PER CHAR(4)NOT NULL PRIMARY KEY CHECK(COD_PER LIKE'P[0-9][0-9][0-9]'),
NOM_PER VARCHAR(30)NOT NULL UNIQUE,
DIR_PER VARCHAR(50)NOT NULL,
DIS_PER CHAR(4)NOT NULL FOREIGN KEY (DIS_PER)REFERENCES DISTRITOS,
CAR_PER CHAR(4)NOT NULL FOREIGN KEY (CAR_PER)REFERENCES CARGOS,
FRE_PER DATETIME DEFAULT(GETDATE())NOT NULL,
EST_PER BIT DEFAULT(1)NOT NULL,
TEL_PER VARCHAR(8) NULL CHEck(TEL_PER LIKE'[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
OBS_PER VARCHAR(50) NULL)
GO
CREATE TABLE CATEGORIAS
(COD_CAT CHAR(4) NOT NULL PRIMARY KEY CHECK(COD_CAT LIKE 'K[0-9][0-9][0-9]'),
NOM_CAT VARCHAR(30) NOT NULL UNIQUE,
DES_CAT VARCHAR(50)NULL)
GO
CREATE TABLE AUTORES
(COD_AUT CHAR(4) NOT NULL PRIMARY KEY CHECK(COD_AUT LIKE 'A[0-9][0-9][0-9]'),
NOM_AUT VARCHAR(30) NOT NULL UNIQUE,
DES_AUT VARCHAR(50)NULL)
GO
CREATE TABLE UBICACION
(COD_UBI CHAR(4) NOT NULL PRIMARY KEY CHECK(COD_UBI LIKE 'U[0-9][0-9][0-9]'),
NOM_UBI VARCHAR(30) NOT NULL UNIQUE,
DES_UBI VARCHAR(50)NULL)
GO
CREATE TABLE LIBROS
(COD_LIB CHAR(4)NOT NULL PRIMARY KEY CHECK(COD_LIB LIKE'L[0-9][0-9][0-9]'),
NOM_LIB VARCHAR(30)NOT NULL UNIQUE,
CAT_LIB CHAR(4)NOT NULL FOREIGN KEY (CAT_LIB)REFERENCES CATEGORIAS,
FIN_LIB DATETIME DEFAULT(GETDATE())NOT NULL,
AUT_LIB CHAR(4)NOT NULL FOREIGN KEY (AUT_LIB)REFERENCES AUTORES,
FPU_LIB DATETIME NOT NULL,
UBI_LIB CHAR(4)NOT NULL FOREIGN KEY (UBI_LIB)REFERENCES UBICACION,
EST_LIB BIT DEFAULT(1)NOT NULL,
CON_LIB BIT DEFAULT(1) NULL,
OBS_LIB VARCHAR(50) NULL)
GO
CREATE TABLE PRESTAMOS
(NRO_PRE CHAR(4)NOT NULL PRIMARY KEY CHECK(NRO_PRE LIKE'N[0-9][0-9][0-9]'),
FRE_PRE DATETIME DEFAULT(GETDATE())NOT NULL,
LEC_PRE CHAR(4)NOT NULL FOREIGN KEY (LEC_PRE)REFERENCES LECTORES,
PER_PRE CHAR(4)NOT NULL FOREIGN KEY(PER_PRE)REFERENCES PERSONAL,
LIB_PER CHAR(4)NOT NULL FOREIGN KEY(LIB_PER)REFERENCES LIBROS,
CON_PRE BIT DEFAULT(1)NOT NULL,
FDE_PRE DATETIME NOT NULL,
EST_PRE BIT DEFAULT(1)NOT NULL,
OBS_PRE VARCHAR(50) NULL)

GO
SP_ADDUSER [UNISISTEMAS],Administrador
go

--CONCEDER PERMISOS PARA EL USUARIO SISTEMASUNI PARA TODOS LOS COMANDOS DML A LAS TABLAS 
-- DE LA BD BIBLIOTECA


GRANT SELECT ON AUTORES TO Administrador
GRANT SELECT ON CARGOS TO Administrador
GRANT SELECT ON CATEGORIAS TO Administrador
GRANT SELECT ON DISTRITOS TO Administrador
GRANT SELECT ON LECTORES TO Administrador
GRANT SELECT ON LIBROS TO Administrador
GRANT SELECT ON PERSONAL TO Administrador
GRANT SELECT ON PRESTAMOS TO Administrador
GRANT SELECT ON TIPOS TO Administrador
GRANT SELECT ON UBICACION TO Administrador

GO
GRANT INSERT,UPDATE,DELETE ON AUTORES TO Administrador
GRANT INSERT,UPDATE,DELETE ON CARGOS TO Administrador
GRANT INSERT,UPDATE,DELETE ON CATEGORIAS TO Administrador
GRANT INSERT,UPDATE,DELETE ON DISTRITOS TO Administrador
GRANT INSERT,UPDATE,DELETE ON LECTORES TO Administrador
GRANT INSERT,UPDATE,DELETE ON LIBROS TO Administrador
GRANT INSERT,UPDATE,DELETE ON PERSONAL TO Administrador
GRANT INSERT,UPDATE,DELETE ON PRESTAMOS TO Administrador
GRANT INSERT,UPDATE,DELETE ON TIPOS TO Administrador
GRANT INSERT,UPDATE,DELETE ON UBICACION TO Administrador

--OTORGAR PERMISOS PARA EL USUARIO Administrador , VISTAS , FUNCIONES , PA EN LA BD
--BIBLIOTECA
GRANT CREATE FUNCTION TO Administrador
GRANT CREATE PROCEDURE,CREATE VIEW TO Administrador
GRANT EXECUTE TO Administrador


--OTORGAR PERMISOS PARA EL USUARIO ADMINISTRADOR PARA CREAR TABLAS
GRANT CREATE TABLE TO Administrador

--DENEGAR INSERTAR LOS REGISTROS
REVOKE INSERT ON DISTRITOS TO Administrador


--ROLES DE SERVIDOR
/*
roles de servidor:

SYSADMIN: PARA CUALQUIER ACTIVIDAD EN EL SERVIDOR
SERVERADMIN: CAMBIAR OPCIONES DE CONFIGURACION EN EL SERVIDOR 
SECURITYADMIN: ADMINISTRAR PERMISOS AL SERVIDOR COMO : GANT , DENY , REVOKE
PROCESASMIN: PUEDE FINALIZAR LOS PROCESOS DE UNA INSTANCIS SQLSERVER
SETUPADMIN: AGREGAR Y QUITAR SERVIDORES VINCULADOS 
DBCREATOR: PERMITE A LA FUNCIONALIDAD DE UNA BD.
*/
--AGREGAR RS SYSADMIN

GO
SP_ADDSRVROLEMEMBER UNISISTEMAS,[sysadmin]

--QUITAR RS SYSADMIN
GO
SP_DROPSRVROLEMEMBER [UNISISTEMAS],[sysadmin]


--AGREGAR RS DBCREATOR , PARA CREAR UNA BD.
GO
SP_ADDSRVROLEMEMBER [UNISISTEMAS],[dbcreator]
GO
SP_DROPSRVROLEMEMBER [UNISISTEMAS],[dbcreator]

GO
--AGREGAR RS SCURITYADMIN , CREAR UN LOGIN SISTEMASUNI
SP_ADDSRVROLEMEMBER [UNISISTEMAS],[securityadmin]
GO
SP_DROPSRVROLEMEMBER [UNISISTEMAS],[securityadmin]