/*==============================================================*/
--AGREGAR FILEGROUPS A LA BD
ALTER DATABASE [ECORP] ADD FILEGROUP DATA_FILEGROUP_V2
GO

--AGREGAR ARCHIVOS SECUNDARIOS A LOS FILEGROUPS
ALTER DATABASE [ECORP]
ADD FILE(
NAME=DATA_FILEGROUP_V2,
FILENAME='C:\database\DATA_FILEGROUP_V2.NDF',
SIZE= 1MB,
MAXSIZE=10MB,
FILEGROWTH=2MB
)TO FILEGROUP DATA_FILEGROUP_V2
GO



/*==============================================================*/
-- VIASUALIZAR LOS FILEGROUPS Y BASES DE DATOS QUE EXISTEN EN EL SERVIDOR
SELECT * FROM sys.sysdatabases
GO
SELECT * FROM sys.filegroups
GO
SP_HELPDB [ECORP]
GO