/*==============================================================*/
--CREA EL SNAPSHOT
-- RECUERDA USAR EL NOMBRE DEL ARCHIVO Y NO EL NOMBRE DE LA BASE DE DATOS PARA CREAR EL SNAPSHOT
USE MASTER;
GO


CREATE DATABASE SNAPSHOT_ECORP_QUINCENA_MARZO_2023 ON 
(
    NAME = 'SNAPSHOT_ECORP_MARCH_2023', --NOMBRE DEL ARCHIVO
    FILENAME = 'C:\database\SNAPSHOT_ECORP_QUINCENA_MARZO_2023.ss'
)
AS SNAPSHOT OF ECORP; --NOMBRE DE LA BASE DE DATOS