

/*==============================================================*/
/*====================CREACIÓN DE BACKUP========================*/

EXECUTE sp_helpDB ECORP

GO
BACKUP DATABASE ECORP
TO DISK='C:\database\ECORP_FULL.BAK'
	WITH NOINT
		NAME='COPIA COMPLETA'
		DESCRIPTION='COPIA DIARIA'

	RESTORE FILELISTONLY
	FROM DISK=''C:\database\ECORP_FULL.BAK'
	GO
	RESTORE HEADERONLY
	FROM DISK='C:\database\ECORP_FULL.BAK'
GO

BACKUP DATABASE ECORP
TO DISK='C:\database\ECORP_FULL.BAK'
	WITH INT
		NAME='COPIA COMPLETA'
		DESCRIPTION='COPIA DIARIA'
		STATS=10,
		FORMAT, COMPRESSION
GO

	RESTORE FILELISTONLY
	FROM DISK=''C:\database\ECORP_FULL2.BAK'
	GO
	RESTORE HEADERONLY
	FROM DISK='C:\database\ECORP_FULL2.BAK' 

GO
BACKUP DATABASE ECORP
TO DISK='C:\database\ECORP_DIFF.BAK'
	WITH DIFFERENTIAL
		NAME='COPIA DIFERENCIAL'
		DESCRIPTION='COPIA DIFERENCIAL PRIMERA SEMANA MARZO'
		INIT
GO

BACKUP DATABASE ECORP
TO DISK='C:\database\ECORP_LOG.BAK'
	WITH NAME='COPIA DEL LOG'
		DESCRIPTION='COPIA LOG PRIMERA SEMANA MARZO'
		INIT
GO
