
/*==============================================================*/
/*==================ADMINISTRACION DE SEGURIDAD======================*/

-- a. Modos de autenticidad



-- b. Creación de Usuarios

USE ECORP
go

CREATE LOGIN AREAOPERACIONES WITH PASSWORD='12345'
GO

-- c. Uso de credenciales y permisos

SP_ADDUSER [AREAOPERACIONES], ADMINISTRADOR
GO
--DAR PERMISOS DE DML A UN USUARIO
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACIONES.EMPLEADOS TO ADMINISTRADOR
GRANT SELECT, INSERT, UPDATE, DELETE ON OPERACIONES.VEHICULOS TO ADMINISTRADOR

-- DENEGAR PERMISOS
REVOKE SELECT, INSERT, UPDATE, DELETE ON OPERACIONES.EMPLEADOS  TO ADMINISTRADOR
REVOKE SELECT, INSERT, UPDATE, DELETE ON OPERACIONES.VEHICULOS TO 	ADMINISTRADOR

--OTORGAR PERMISOS PARA EL USUARIO , VISTAS , FUNCIONES , PROCEDIMIENTO ALMACENADO 

GRANT CREATE TABLE, CREATE FUNCTION, CREATE PROCEDURE, CREATE VIEW, EXECUTE TO ADMINISTRADOR

--DENEGAR PERMISOS PARA EL USUARIO , VISTAS , FUNCIONES , PROCEDIMIENTO ALMACENADO

REVOKE CREATE TABLE, CREATE FUNCTION, CREATE PROCEDURE, CREATE VIEW, EXECUTE TO ADMINISTRADOR
GO

-- d. Roles del servidor


--AGREGAR AL NUEVO USUARIO COMO SYSADMIN

SP_ADDSRVROLEMEMBER AREAOPERACIONES,[sysadmin]

-- QUITAR RS SYSADMIN
SP_DROPSRVROLEMEMBER AREAOPERACIONES, [sysadmin]
GO
-- AGREGAR RS DBCREATOR, PARA CREAR UNA BD
SP_ADDSRVROLEMEMBER AREAOPERACIONES,[dbcreator]
GO
SP_DROPSRVROLEMEMBER AREAOPERACIONES,[dbcreator]
GO

-- AGREGAR RS SCURITYADMIN, CREAR UN LOGIN 
SP_ADDSRVROLEMEMBER AREAOPERACIONES,[securityadmin]
GO

SP_DROPSRVROLEMEMBER AREAOPERACIONES, [securityadmin]


-- e. Beneficios de la automatización
--La automatización permite 




