
USE neptuno2

-- VAMOS A CREAR LA TABLA TBLCIENTES .

SELECT * INTO TBLCLIENTES FROM CLIENTES

SELECT * FROM TBLCLIENTES

--TRUNCATE -- (DELETE)

TRUNCATE TABLE TBLCLIENTES

--CONSULTAR LOS PEDIDOS

SELECT P.IdPedido,P.FechaPedido,P.IdEmpleado,C.idCliente,C.NombreCompañia,C.Pais 
FROM neptuno.dbo.Pedidos P INNER JOIN neptuno.dbo.clientes C ON P.IdCliente=
C.idCliente WHERE YEAR(P.FechaPedido)=1995

SELECT P.IdPedido,P.FechaPedido,P.IdEmpleado,C.idCliente,C.NombreCompañia,C.Pais 
INTO TBLPEDIDOS_CLIENTE FROM neptuno.dbo.Pedidos P INNER JOIN neptuno.dbo.clientes C ON 
P.IdCliente=C.idCliente WHERE YEAR(P.FechaPedido)=0
GO


-- C:/>BCP BD_LATAM.DBO.TBLCIUDAD OUT D:/DATO/TBLCIUDAD_DATA.TXT -S . -T -c
-- 1. CAMBIAR EL COMA A PUNTO


SELECT * FROM TBLPEDIDOS_CLIENTE

--
TRUNCATE TABLE TBLPEDIDOS_CLIENTE


--CARGA MASIVAS
BULK INSERT TBLPEDIDOS_CLIENTE
FROM 'D:\SESION_6\PEDIDOS_CLIENTE_1995.TXT'
--WITH