
USE neptuno2

-- VAMOS A CREAR LA TABLA TBLCIENTES .

SELECT * INTO TBLCLIENTES FROM CLIENTES

SELECT * FROM TBLCLIENTES

--TRUNCATE -- (DELETE)

TRUNCATE TABLE TBLCLIENTES

--CONSULTAR LOS PEDIDOS

SELECT P.IdPedido,P.FechaPedido,P.IdEmpleado,C.idCliente,C.NombreCompañia,C.Pais 
FROM neptuno.dbo.Pedidos P INNER JOIN neptuno.dbo.clientes C ON P.IdCliente=
C.idCliente WHERE YEAR(P.FechaPedido)=1995


--USANDO EL CLI BCP
-- BCP BD_LATAM.DBO.TBLCIUDAD OUT C:\database\TBLCIUDAD_DATA.TXT -S . -T -c

/*
BCP "SELECT P.IdPedido,P.FechaPedido,P.IdEmpleado,C.idCliente,C.NombreCompañia,C.Pais 
FROM neptuno.dbo.Pedidos P INNER JOIN neptuno.dbo.clientes C ON P.IdCliente=
C.idCliente WHERE YEAR(P.FechaPedido)=1995" QUERYOUT C:\database\PEDIDOS_CLIENTES_1995.TXT -S . -T -c 
 */


--CREAMOS LA TABLA TBLPEDIDOS_CLIENTE
SELECT P.IdPedido,P.FechaPedido,P.IdEmpleado,C.idCliente,C.NombreCompañia,C.Pais 
INTO TBLPEDIDOS_CLIENTE FROM neptuno2.dbo.Pedidos P INNER JOIN neptuno2.dbo.clientes C ON 
P.IdCliente=C.idCliente WHERE YEAR(P.FechaPedido)=0
GO

 -- INSERTAR DATOS 

SELECT * FROM TBLPEDIDOS_CLIENTE


--CARGA MASIVA USANDO EL CLI BCP
--BCP NEPTUNO2.DBO.TBLPEDIDOS_CLIENTE IN C:\database\PEDIDOS_CLIENTES_1995.TXT -S . -T -c

--VERIFICAMOS SI SE CARGO LOS DATOS DE LA TABLA
SELECT * FROM TBLPEDIDOS_CLIENTE


--ELIMINAR TODOS LOS REGISTROS Y NO LA TABLA
TRUNCATE TABLE TBLPEDIDOS_CLIENTE


--CARGA MASIVAS	CON SENTENCIA
BULK INSERT TBLPEDIDOS_CLIENTE
FROM 'C:\database\PEDIDOS_CLIENTES_1995.TXT'

--VERIFICAMOS SI SE CARGO LOS DATOS DE LA TABLA
SELECT * FROM TBLPEDIDOS_CLIENTE