--PLANIFICACION BD

-- if database EXCULA exists, drop it
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'ESCUELA')
BEGIN
    DROP DATABASE ESCUELA
END

CREATE DATABASE ESCUELA
ON(
NAME='ESCUELA_DATA',
FILENAME='C:\Users\joel_\Desktop\database\ESCUELA_DATA.MDF',
SIZE=5MB,
MAXSIZE=15MB,
FILEGROWTH=50%
)
LOG ON(
NAME='ESCUELA_LOG',
FILENAME='C:\Users\joel_\Desktop\database\ESCUELA_LOG.LDF',
SIZE=5MB,
MAXSIZE=15MB,
FILEGROWTH=2MB
);

GO



--EJEMPLO 2 (Crea tu base de datos fisico y logico en tu ruta de preferencia)

IF EXISTS (SELECT * FROM sys.databases WHERE name = 'BD_TIENDA')
BEGIN
    DROP DATABASE BD_TIENDA
END

CREATE DATABASE BD_TIENDA
ON(
NAME='BD_TIENDA_DATA',
FILENAME='C:\Users\joel_\Desktop\database\BD_TIENDA_DATA.MDF',
SIZE=6MB,
MAXSIZE=25MB,
FILEGROWTH=60%
)
LOG ON(
NAME='BD_TIENDA_LOG',
FILENAME='C:\Users\joel_\Desktop\database\BD_TIENDA_LOG.LDF',
SIZE=6MB,
MAXSIZE=25MB,
FILEGROWTH=4MB
)