
--CREAR FILEGROUPS

--AGREGAR FILEGROUPS A LA BD
ALTER DATABASE [BD_TIENDA] ADD FILEGROUP DATA_1
GO
ALTER DATABASE  [BD_TIENDA] ADD FILEGROUP DATA_2
GO
USE MASTER
USE ESCUELA
USE BD_TIENDA
SELECT * FROM sys.filegroups

--AGREGAR ARCHIVOS SECUNDARIOS A LOS FILEGROUPS

ALTER DATABASE [BD_TIENDA]
ADD FILE(
NAME=DATA1,
FILENAME='C:\Users\joel_\Desktop\database\DATA1.NDF',
SIZE= 1MB,
MAXSIZE=10MB,
FILEGROWTH=2MB
)TO FILEGROUP DATA_1

GO
ALTER DATABASE [BD_TIENDA]
ADD FILE(
NAME=DATA2,
FILENAME='C:\Users\joel_\Desktop\database\DATA2.NDF',
SIZE=1MB,
MAXSIZE=10MB,
FILEGROWTH=2MB
)TO FILEGROUP DATA_2
