
--ESTABLECER EL ROL DE NUEVO USUARIO COMO ADMINISTRADOR
SP_ADDUSER [UNISISTEMAS], Administrador
go

--CONCEDER PERMISOS PARA EL USUARIO SISTEMASUNI PARA TODOS LOS COMANDOS DML A LAS TABLAS 
-- DE LA BD BIBLIOTECA


GRANT SELECT ON AUTORES TO Administrador
GRANT SELECT ON CARGOS TO Administrador
GRANT SELECT ON CATEGORIAS TO Administrador
GRANT SELECT ON DISTRITOS TO Administrador
GRANT SELECT ON LECTORES TO Administrador
GRANT SELECT ON LIBROS TO Administrador
GRANT SELECT ON PERSONAL TO Administrador
GRANT SELECT ON PRESTAMOS TO Administrador
GRANT SELECT ON TIPOS TO Administrador
GRANT SELECT ON UBICACION TO Administrador

GO
GRANT INSERT,UPDATE,DELETE ON AUTORES TO Administrador
GRANT INSERT,UPDATE,DELETE ON CARGOS TO Administrador
GRANT INSERT,UPDATE,DELETE ON CATEGORIAS TO Administrador
GRANT INSERT,UPDATE,DELETE ON DISTRITOS TO Administrador
GRANT INSERT,UPDATE,DELETE ON LECTORES TO Administrador
GRANT INSERT,UPDATE,DELETE ON LIBROS TO Administrador
GRANT INSERT,UPDATE,DELETE ON PERSONAL TO Administrador
GRANT INSERT,UPDATE,DELETE ON PRESTAMOS TO Administrador
GRANT INSERT,UPDATE,DELETE ON TIPOS TO Administrador
GRANT INSERT,UPDATE,DELETE ON UBICACION TO Administrador

--OTORGAR PERMISOS PARA EL USUARIO Administrador , VISTAS , FUNCIONES , PROCEDIMIENTO ALMACENADO 
-- EN LA BD BIBLIOTECA
GRANT CREATE FUNCTION TO Administrador
GRANT CREATE PROCEDURE,CREATE VIEW TO Administrador
GRANT EXECUTE TO Administrador


--OTORGAR PERMISOS PARA EL USUARIO ADMINISTRADOR PARA CREAR TABLAS
GRANT CREATE TABLE TO Administrador


--DENEGAR INSERTAR LOS REGISTROS
REVOKE INSERT ON DISTRITOS TO Administrador


--ROLES DE SERVIDOR
/*
roles de servidor:

SYSADMIN: PARA CUALQUIER ACTIVIDAD EN EL SERVIDOR
SERVERADMIN: CAMBIAR OPCIONES DE CONFIGURACION EN EL SERVIDOR 
SECURITYADMIN: ADMINISTRAR PERMISOS AL SERVIDOR COMO : GANT , DENY , REVOKE
PROCESASMIN: PUEDE FINALIZAR LOS PROCESOS DE UNA INSTANCIS SQLSERVER
SETUPADMIN: AGREGAR Y QUITAR SERVIDORES VINCULADOS 
DBCREATOR: PERMITE A LA FUNCIONALIDAD DE UNA BD.
*/
--AGREGAR RS SYSADMIN

GO
SP_ADDSRVROLEMEMBER UNISISTEMAS,[sysadmin]

--QUITAR RS SYSADMIN
GO
SP_DROPSRVROLEMEMBER [UNISISTEMAS],[sysadmin]


--AGREGAR RS DBCREATOR , PARA CREAR UNA BD.
GO
SP_ADDSRVROLEMEMBER [UNISISTEMAS],[dbcreator]
GO
SP_DROPSRVROLEMEMBER [UNISISTEMAS],[dbcreator]

GO
--AGREGAR RS SCURITYADMIN , CREAR UN LOGIN SISTEMASUNI
SP_ADDSRVROLEMEMBER [UNISISTEMAS],[securityadmin]
GO
SP_DROPSRVROLEMEMBER [UNISISTEMAS],[securityadmin]