

--ROLES DE SERVIDOR
-- RECUERDA QUE TODO DEBE SER EJECUTADO DESDE EL SERVIDOR PRINCIPAL
/*
roles de servidor:

SYSADMIN: PARA CUALQUIER ACTIVIDAD EN EL SERVIDOR
SERVERADMIN: CAMBIAR OPCIONES DE CONFIGURACION EN EL SERVIDOR 
SECURITYADMIN: ADMINISTRAR PERMISOS AL SERVIDOR COMO : GANT , DENY , REVOKE
PROCESASMIN: PUEDE FINALIZAR LOS PROCESOS DE UNA INSTANCIS SQLSERVER
SETUPADMIN: AGREGAR Y QUITAR SERVIDORES VINCULADOS 
DBCREATOR: PERMITE A LA FUNCIONALIDAD DE UNA BD.
*/
--AGREGAR RS SYSADMIN


SP_ADDSRVROLEMEMBER UNISISTEMAS,[sysadmin]
GO

--QUITAR RS SYSADMIN

SP_DROPSRVROLEMEMBER [UNISISTEMAS],[sysadmin]
GO

--AGREGAR RS DBCREATOR , PARA CREAR UNA BD.

SP_ADDSRVROLEMEMBER [UNISISTEMAS],[dbcreator]
GO


SP_DROPSRVROLEMEMBER [UNISISTEMAS],[dbcreator]
GO

--AGREGAR RS SCURITYADMIN , DAR PERMISOS PARA CREAR NUEVOS USUARIOS
SP_ADDSRVROLEMEMBER [UNISISTEMAS],[securityadmin]
GO


SP_DROPSRVROLEMEMBER [UNISISTEMAS],[securityadmin]
GO