
/*==============================================================*/
/*==================RESTAURACIÓN DE BACKUP======================*/
--EJECUTAR DESDE MASTER
USE MASTER
GO

--RESTAURAR EL BACKUP
RESTORE DATABASE BD_ECORP
FROM DISK = 'C:\database\BD_ECORP_FULL.BAK'
WITH REPLACE, NORECOVERY 


--RESTAURAR EL BACKUP DIFERENCIAL
RESTORE DATABASE BD_ECORP
FROM DISK = 'C:\database\BD_ECORP_DIFF.BAK'
WITH NORECOVERY


--RESTAURAR EL BACKUP DE LOS REGISTROS
RESTORE LOG BD_ECORP
FROM DISK = 'C:\database\BD_ECORP_LOG.BAK'
WITH NORECOVERY
GO


RESTORE LOG BD_ECORP
WITH RECOVERY;	   --SE UTILIZA CUANDO YA SE FINALIZA LA RESTAURACIÓN


--COMPROBANDO LA RESTAURACIÓN
USE BD_ECORP

SELECT * FROM TBLCIUDAD