
/*==============================================================*/
/*====================CREACIÓN DE BACKUP========================*/
--BACKUP COMPRIMIDO
 BACKUP DATABASE BD_ECORP
 TO DISK= 'C:\database\BD_ECORP_FULL.BAK'
	WITH INIT,
	NAME='COPIA COMPLETA',
	DESCRIPTION='COPIA DIARIA DE LA BASE DE DATOS ECORP',
	STATS=10,
	FORMAT, COMPRESSION
GO

-- BACKUP DIFERENCIAL
BACKUP DATABASE ECORP
TO DISK = 'C:\database\BD_ECORP_DIFF.BAK'
    WITH DIFFERENTIAL,
    NAME='COPIA DIFERENCIAL',
    DESCRIPTION='COPIA DIFERENCIA DE LA BASE DE DATOS ECORP',
    INIT
GO

-- BACKUP DE LOS REGISTROS
BACKUP LOG BD_ECORP
TO DISK = 'C:\database\BD_ECORP_LOG.BAK'
    WITH NAME = 'COPIA DEL LOG',
    DESCRIPTION='COPIA LOG DE LA BASE DE DATOS ECORP',
    INIT



-- EL FILELISTONLY LISTA LA INFORMACION DE ARCHIVOS QUE SE COPIARON EN LA COPIA DE SEGURIDAD (BACKUP)
RESTORE FILELISTONLY
FROM DISK= 'C:\database\BD_ECORP_FULL.BAK'
GO

-- HEADERONLY MUESTRA EL ENCABEZADO (EL NAME) DE LA COPIA DE SEGURIDAD (BACKUP)
RESTORE HEADERONLY
FROM DISK= 'C:\database\BD_ECORP_FULL.BAK'
GO