CREATE DATABASE SUPERMERCADO;

USE SUPERMERCADO;

CREATE TABLE DISTRITOS(
CODDIS CHAR(4) PRIMARY KEY,
NOMDIS VARCHAR(25) NOT NULL
);

CREATE TABLE CARGOS(
CODCAR CHAR(4) PRIMARY KEY,
NOCAR VARCHAR(30) NOT NULL
);

CREATE TABLE MARCAS(
CODMAR CHAR(4) PRIMARY KEY, 
NOMMAR VARCHAR(30) NOT NULL
);

CREATE TABLE CATEGORIAS(
CODCAT CHAR(4) PRIMARY KEY,
NOMCAT VARCHAR(30) NOT NULL
);

CREATE TABLE FORMA_PAGO(
CODFOR CHAR(4) PRIMARY KEY,
NOMFOR VARCHAR(25) NOT NULL
);

CREATE TABLE LOCALES(
CODLOC CHAR(4) PRIMARY KEY,
NOMLOC VARCHAR(30) NOT NULL,
DIREC VARCHAR(40) NOT NULL,
CODDIS CHAR(4),
TELEF VARCHAR(9) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
FOREIGN KEY (CODDIS) REFERENCES DISTRITOS(CODDIS)
);



CREATE TABLE CLIENTES(
CODCLI CHAR(4) PRIMARY KEY,
NOMCLI VARCHAR(40) NOT NULL,
DIREC VARCHAR(40) NOT NULL,
CODDIS CHAR(4) REFERENCES DISTRITOS(CODDIS),
FNAC DATE NOT NULL,
SEXO CHAR(1) NOT NULL,
TELEF VARCHAR(9) NOT NULL
);

CREATE TABLE PERSONAL(
CODPER CHAR(4) PRIMARY KEY,
NOMPER VARCHAR(40) NOT NULL,
DIREC VARCHAR(40) NOT NULL,
CODDIS CHAR(4) REFERENCES DISTRITOS(CODDIS),
FNAC  DATE NOT NULL,
SEXO CHAR(1) NOT NULL,
CODCAR CHAR(4) REFERENCES CARGOS(CODCAR),
SUELDO DECIMAL(7,2) NOT NULL
);

CREATE TABLE PRODUCTOS(
CODPROD CHAR(6) PRIMARY KEY,
NOMPROD VARCHAR(40) NOT NULL,
CODMAR CHAR(4) REFERENCES MARCAS(CODMAR),
CODCAT CHAR(4) REFERENCES CATEGORIAS(CODCAT),
PRECIO DECIMAL(7,2) NOT NULL,
STOCK INT NOT NULL
);

CREATE TABLE COMP_CABECERA(
CODCOM CHAR(6) PRIMARY KEY,
CODCLI CHAR(4) REFERENCES CLIENTES(CODCLI),
CODPER CHAR(4) REFERENCES PERSONAL(CODPER),
CODLOC CHAR(4) REFERENCES LOCALES(CODLOC),
CODFOR CHAR(4) REFERENCES FORMA_PAGO(CODFOR),
TIPO_COMP CHAR(1) NOT NULL,
FECHA DATE NOT NULL
);

CREATE TABLE COMP_DETALLE(
CODCOM CHAR(6) REFERENCES COMP_CABECERA(CODCOM),
CODPROD CHAR(6) REFERENCES PRODUCTOS(CODPROD),
CANTIDAD INT NOT NULL,
PRECIO DECIMAL(7,2) NOT NULL,
DCTO DECIMAL(6,2) NOT NULL
);
GO

