  
USE SUPERMERCADO
GO

--TRIGGERS

--EJERCICIO 1
/*
CREAR UN TRIGGER QUE IMPRIMA UN MENSAJE CUANDO 
UNA MARCA NUEVA SE GRABE.
*/

CREATE TRIGGER GRABA_MARCA ON [dbo].[MARCAS]
FOR INSERT
AS
PRINT 'SE GRABO UNA NUEVA MARCA'
GO

--EJECUTAR TRIGGER GRABA_MARCA
INSERT INTO MARCAS VALUES('M001','REXONA')
GO

------------------------------------------------------
--EJERCICIO 2
/*
CREAR UN TRIGGER QUE IMPRIMA UN MENSAJE CUANDO SE MODIFIQUE 
EL NOMBRE DE UNA MARCA.
*/

CREATE TRIGGER MODIFICA_MARCA ON [dbo].[MARCAS]
FOR UPDATE
AS
PRINT 'SE MODIFICO UNA MARCA'


--EJECUTAR TRIGGER MODIFICA_MARCA
UPDATE MARCAS SET NOMMAR = 'ROSAS Y LIMON' WHERE CODMAR = 'M001'

SELECT * FROM MARCAS
GO

--EJERCICIO 3
/*
CREAR UN TRIGGER QUE IMPRIMA LOS DATOS ANTIGUOS Y NUEVOS CUANDO 
SE MODIFIQUE UN DISTRITO. 
TABLA INSERTED : GUARDA DATOS NUEVOS INSERTADOS.
TABLA DELETED   : GUARDA DATOS ANTIGUOS ELIMINADOS.
*/


CREATE TRIGGER MODIFICA_DISTRITO 
ON [dbo].[DISTRITOS]
    FOR UPDATE
    AS
        DECLARE @COD CHAR(4), @NOM VARCHAR(25)
        SELECT @COD = CODDIS, @NOM = NOMDIS FROM DELETED
        PRINT 'SE MODIFICO EL DISTRITO '
        PRINT 'DATOS ANTIGUOS'
        PRINT '-------------------------------'
        PRINT 'CODIGO    :' + @COD
        PRINT 'NOMBRE    :' + @NOM

        SELECT @COD=CODDIS, @NOM=NOMDIS FROM INSERTED
        PRINT 'DATOS NUEVOS'
        PRINT '-------------------------------'
        PRINT 'CODIGO    :' + @COD
        PRINT 'NOMBRE    :' + @NOM
GO

INSERT INTO DISTRITOS VALUES('D001', 'SAN JUAN DE LURIGANCHO')
GO

SELECT * FROM DISTRITOS

--EJECUTAR TRIGGER MODIFICA_DISTRITO
UPDATE DISTRITOS SET NOMDIS = 'SAN JUAN' WHERE CODDIS = 'D001'
GO

--EJERCICIO 4
/*
CREAR UN TRIGGER QUE IMPRIMA EL DATO ANTIGUO Y NUEVO CUANDO
DE MODIFIQUE EL PRECIO DE UN PRODUCTO.
-- SOLUCION A)
*/
CREATE TRIGGER MODIFICA_PRECIO
ON [dbo].[PRODUCTOS]
    FOR UPDATE
    AS
        DECLARE @PREANT DECIMAL(7,2), @PRECNUE DECIMAL(7,2)
        SELECT @PREANT = PRECIO FROM DELETED   
        SELECT @PRECNUE = PRECIO FROM INSERTED
        IF @PREANT <> @PRECNUE	  --SOLO SE IMPRIME SI SON DIFERENTES
        BEGIN
            PRINT 'SE MODIFICO EL PRECIO DE UN PRODUCTO'
            PRINT 'PRECIO ANTIGUO: ' + STR(@PREANT, 10, 2)
            PRINT 'PRECIO NUEVO: ' + STR(@PRECNUE, 10, 2)
        END
GO



CREATE TRIGGER MODIFICA_PRECIO01
ON [dbo].[PRODUCTOS]
	FOR UPDATE
	AS
		IF (UPDATE(PRECIO))		 -- SE IMPRIME SI HAY ALGUN UPDATE
			BEGIN
				DECLARE @PREANT DECIMAL(7,2),@PRECNUE DECIMAL(7,2)
				SELECT @PREANT=PRECIO FROM deleted
				SELECT @PRECNUE=PRECIO FROM inserted

				PRINT 'SE MODIFICO EL PRECIO DE UN PRODUCTO'
				PRINT 'PRECIO ANTIGUO:'+ STR(@PREANT,7,2)
				PRINT 'PRECIO NUEVO:'+STR(@PRECNUE,7,2)
			END
GO

--ELIMINAR UN TRIGGER
DROP TRIGGER MODIFICA_PRECIO
DROP TRIGGER MODIFICA_PRECIO01


--PARA VER SI EL TRIGGER EXISTE, SI EXISTE DEVUELVE NULL
SELECT OBJECT_ID('dbo.MODIFICA_PRECIO', 'TR');



INSERT INTO CATEGORIAS VALUES('C001','DESODORANTE')

INSERT INTO PRODUCTOS
VALUES
('P001','REXONA','M001','C001',5.00,100),
('P002','DESODORANTE','M001','C001',5.00,100),
('P003','DESODORANTE','M001','C001',5.00,100); 


--EJECUTAR TRIGGER MODIFICA_PRECIO
UPDATE PRODUCTOS SET PRECIO = 10.00 WHERE CODPROD = 'P001'
GO




--EJEMPLO 5
/*
CREAR UN TRIGGER QUE IMPRIMA EL DATO ANTIGUO Y NUEVO
CUANDO SE MODIFIQUE EL TELEFONO DE UN CLIENTE.
*/
CREATE TRIGGER MODIFICA_TELEFONO
ON [dbo].[CLIENTES]
FOR UPDATE
AS
    DECLARE @TELEFANT VARCHAR(9), @TELEFNUE VARCHAR(9)
    SELECT @TELEFANT = TELEF FROM DELETED
    SELECT @TELEFNUE = TELEF FROM INSERTED
    IF @TELEFANT <> @TELEFNUE
    BEGIN
        PRINT 'SE MODIFICO EL TELEFONO DE UN CLIENTE'
        PRINT 'TELEFONO ANTIGUO: ' + @TELEFANT
        PRINT 'TELEFONO NUEVO: ' + @TELEFNUE
    END
GO


--INSERT 2 ROWS FOR CLIENTES
INSERT INTO CLIENTES 
VALUES
('C001','JUAN PEREZ','AV. LA MARINA 123','D001','1990-01-01','M','123456789'),
('C002','PEDRO GOMEZ','AV. LA MARINA 456','D001','1990-01-01','M','123456789');
GO

--EJECUTAR TRIGGER MODIFICA_TELEFONO
UPDATE CLIENTES SET TELEF = '987654321' WHERE CODCLI = 'C001'
GO



--EJEMPLO 6
/*
CREAR UN TRIGGER QUE NO PERMITA MODIFICAR EL SUELDO DE UN 
PERSONAL.
*/
CREATE TRIGGER MODIFICAR_SUELDO
ON [dbo].[PERSONAL]
FOR UPDATE
    AS
    IF(UPDATE([SUELDO]))
    BEGIN
        PRINT 'NO SE PUEDE MODIFICAR EL SUELDO'
		ROLLBACK TRANSACTION
    END
GO

DROP TRIGGER   MODIFICAR_SUELDO


INSERT INTO PERSONAL
VALUES
('P001','JUAN PEREZ','AV. LA MARINA 123','D001','1990-01-01','M','C001',1000),
('P002','PEDRO GOMEZ','AV. LA MARINA 456','D001','1990-01-01','M','C001',1000);
GO

--EJECUTAR TRIGGER MODIFICAR_SUELDO
UPDATE PERSONAL SET SUELDO = 1000 WHERE CODPER = 'P001'
GO


--EJEMPLO 7
/*
CREAR UN TRIGGER QUE PERMITA ELIMINAR UNA 
SOLA MARCA CUANDO SE REALICE UN DELETE.
ESTA PROHIBIDO : DELETE 
FROM MARCAS WHERE CODMAR IN ('M006', 'M007')
*/

CREATE TRIGGER ELIMINA_MARCA
ON [dbo].[MARCAS]
    FOR DELETE
    AS 
    IF((SELECT COUNT(CODMAR) FROM DELETED) > 1)
		BEGIN
			ROLLBACK TRANSACTION
			RAISERROR('NO SE PUEDE ELIMINAR MAS DE UNA MARCA', 16, 1)
            PRINT 'NO SE PUEDE ELIMINAR MAS DE UNA MARCA'
            --DIFERENTES MANERAS DE IMPRIMIR UN MENSAJE
		END
GO

DROP TRIGGER  ELIMINA_MARCA


INSERT INTO MARCAS VALUES('M002','DESODORANTE')
INSERT INTO MARCAS VALUES('M003','DESODORANTE')
INSERT INTO MARCAS VALUES('M004','DESODORANTE')

--EJECUTAR TRIGGER ELIMINA_MARCA
DELETE FROM MARCAS WHERE NOMMAR = 'DESODORANTE'


