	
--DEMO 2
CREATE DATABASE COLEGIO_UNI
GO
USE COLEGIO_UNI

CREATE TABLE ALUMNO(
IDALUMNO INT IDENTITY NOT NULL,
DNI NVARCHAR(8) NOT NULL,
APPATERNO NVARCHAR(50) NOT NULL,
APMATERNO NVARCHAR(50) NOT NULL,
EDAD INT,
ESTADO BIT 

)

CREATE TABLE NOTA(
CODNOTA INT NOT NULL,
IDALUMNO INT NOT NULL,
CODCURSO INT NOT NULL,
NOTA INT NOT NULL,
OBSERVACION VARCHAR(50) NOT NULL
)

CREATE TABLE CURSO(
CODCURSO INT NOT NULL,
NOMBRECURSO VARCHAR(50) UNIQUE NOT NULL,
FECHA_INI DATE NOT NULL,
FECHA_FINAL DATE NOT NULL,
COSTOCURSO MONEY NOT NULL
)

CREATE TABLE HISTORICO_ALUMNO(
    IDALUMNO INT IDENTITY,
    DNI NVARCHAR(8) NOT NULL,
    APPARTERNO NVARCHAR(50) NOT NULL,
    APMATERNO NVARCHAR(50) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    EDAD INT,
    ESTADO BIT,
    FECHAMODIFICACION DATETIME,
    VACACION NVARCHAR(50)
)



SELECT * FROM ALUMNO
SELECT * FROM CURSO
SELECT * FROM NOTA

--CREANDO LA PK

/* SINTAXIS

ALTER TABLE NOMBRE_TABLA
ADD CONSTRAINT PK_NOMBRE_TABLA
PRIMARY KEY(COLUMNAX,COLUMNAP,...)
*/
--PK ALUMNO
ALTER TABLE ALUMNO ADD CONSTRAINT PK_ALUMNO PRIMARY KEY(IDALUMNO)
--PK NOTA
ALTER TABLE NOTA ADD CONSTRAINT PK_NOTA PRIMARY KEY(CODNOTA)
--PK CURSO
ALTER TABLE CURSO ADD CONSTRAINT PK_CURSO PRIMARY KEY(CODCURSO)

--LLAVE FORANEA (FK)
/*
ALTER TABLE NOMBRE_TABLA
ADD CONSTRAINT FK_NOMBRE_TABLA_TABLA REFERENCIADA
FOREIGN KEY(COLUMNAX,COLUMNA P)
*/
ALTER TABLE NOTA
ADD CONSTRAINT FK_NOTA_CURSO
FOREIGN KEY(CODCURSO)
REFERENCES CURSO(CODCURSO)

--ALTER AUTHORIZATION ON DATABASE::COLEGIO_UNI TO SA

ALTER TABLE NOTA
ADD CONSTRAINT FK_NOTA_ALUMNO
FOREIGN KEY(CODALUMNO)
REFERENCES ALUMNO(CODALUMNO)

--INGRESAR REGISTROS

SELECT * FROM ALUMNO

INSERT INTO ALUMNO VALUES('1000','02/10/2019','MARITZA','AGUILAR ROJAS')
INSERT INTO ALUMNO VALUES('1001','02/11/2019','MIGUEL','CUADROS SOLANO')
INSERT INTO ALUMNO VALUES('1002','02/12/2019','DIEGO','VIVANCO FLORES')
INSERT INTO ALUMNO VALUES('1003','02/01/2019','ANDERSON','TORRES JUARES')
INSERT INTO ALUMNO VALUES('1004','02/02/2019','WILLY','CASAS URBINA')

SELECT * FROM CURSO

INSERT INTO CURSO VALUES('100','MODELAMIENTO DE DATOS','01/01/2019','01/30/2019','300')
INSERT INTO CURSO VALUES('101','IMPLEMENTACION SQL ','01/02/2019','01/28/2019','300')
INSERT INTO CURSO VALUES('102','ADMINISTRACION ','01/03/2019','01/30/2019','380')
INSERT INTO CURSO VALUES('103','INTELIGENCIA DE NEGOCIOS ','01/04/2019','01/30/2019','400')

SELECT * FROM NOTA

INSERT INTO NOTA VALUES('050','1000','100',15,'')
INSERT INTO NOTA VALUES('051','1001','100',16,'')
INSERT INTO NOTA VALUES('052','1002','102',20,'')
INSERT INTO NOTA VALUES('053','1003','102',08,'REQUIERE VOLVER A TOMAR EL CURSO')





--IMPLEMENTAR TRIGGER AUDITORIA | HISTORICO ALUMNO
-- CREATE TRIGGER AUDITORIA_COLEGIO_UNI
-- ON [dbo].[ALUMNO]
-- AFTER INSERT, UPDATE
--     AS BEGIN 
--         BEGIN 
--             IF EXISTS(SELECT 1 FROM DELETED)
--                 BEGIN 
--                     INSERT INTO HISTORICO_ALUMNO(DNI,APPATERNO,APMATERNO,NOMBRE, EDAD,ESTADO,FECHAMODIFICACION,VACACION)
--                     SELECT D.DNI ,D.APPATERNO,D.APMATERNO,D.NOMBRE,D.EDAD,D.ESTADO,GETDATE(),'NO'
--                     (CASE WHEN 
                    )