

--IMPLEMENTAR TRIGGER AUDITORIA | HISTORICO ALUMNO
USE	[COLEGIO_UNI]
GO


CREATE TRIGGER AUDITORIA_COLEGIO_UNI
	ON [dbo].[ALUMNO]
		AFTER INSERT,UPDATE --DESPUES DE UN INSERT O UPDATE SE EJECUTA EL CODIGO SIGUIENTE
			AS 
				BEGIN
					IF EXISTS(SELECT 1 FROM deleted) -- EL 1 SIGNIFICA UN TRUE, SI EXISTE UN REGISTRO EN LA TABLA TEMPORAL DELETED
						-- SI NO HAY NINGUN DELETED ENTONCES E VA AL ELSE
						BEGIN
							INSERT INTO HISTORICO_ALUMNO
							([DNI],[APPATERNO],[APMATERNO],[NOMBRES],[EDAD],[ESTADO],[FECHAMODIFICACION],[VACCION])
							SELECT D.DNI, D.APPATERNO, D.APMATERNO, D.NOMBRES, D.EDAD, D.ESTADO, GETDATE(),
								(CASE WHEN
									I.ESTADO=0 THEN 'ELIMINADO' --LA COLUMNA ESTADO PUEDEN SER 0 O 1
								ELSE
									'MODIFICADO'
								END) AS VACCION 
							FROM deleted D JOIN inserted I ON D.DNI=I.DNI
						END
					ELSE
						BEGIN
							INSERT INTO HISTORICO_ALUMNO
							([DNI],[APPATERNO],[APMATERNO],[NOMBRES],[EDAD],[ESTADO],[FECHAMODIFICACION],[VACCION])
							SELECT I.DNI,I.APPATERNO,I.APMATERNO,I.NOMBRES,I.EDAD,I.ESTADO,GETDATE(),'INSERTADO' AS VACCION
							FROM inserted I
						END
				END






INSERT INTO ALUMNO([DNI],[APPATERNO],[APMATERNO],[NOMBRES],[EDAD],[ESTADO])
VALUES('40623588','AGUILAR','ROJAS','LILIANA',35,1)

--INGRESAR REGISTROS

SELECT * FROM ALUMNO
SELECT * FROM HISTORICO_ALUMNO

UPDATE ALUMNO SET EDAD=25 WHERE DNI='40623588'








INSERT INTO ALUMNO VALUES('1001','02/11/2019','MIGUEL','CUADROS SOLANO')
INSERT INTO ALUMNO VALUES('1002','02/12/2019','DIEGO','VIVANCO FLORES')
INSERT INTO ALUMNO VALUES('1003','02/01/2019','ANDERSON','TORRES JUARES')
INSERT INTO ALUMNO VALUES('1004','02/02/2019','WILLY','CASAS URBINA')

SELECT * FROM CURSO

INSERT INTO CURSO VALUES('100','MODELAMIENTO DE DATOS','01/01/2019','01/30/2019','300')
INSERT INTO CURSO VALUES('101','IMPLEMENTACION SQL ','01/02/2019','01/28/2019','300')
INSERT INTO CURSO VALUES('102','ADMINISTRACION ','01/03/2019','01/30/2019','380')
INSERT INTO CURSO VALUES('103','INTELIGENCIA DE NEGOCIOS ','01/04/2019','01/30/2019','400')

SELECT * FROM NOTA

INSERT INTO NOTA VALUES('050','1000','100',15,'')
INSERT INTO NOTA VALUES('051','1001','100',16,'')
INSERT INTO NOTA VALUES('052','1002','102',20,'')
INSERT INTO NOTA VALUES('053','1003','102',08,'REQUIERE VOLVER A TOMAR EL CURSO')

GO