-- CREATE DATABASE VENTAS
-- GO


IF EXISTS (SELECT * FROM sys.databases WHERE name = 'VENTAS')
BEGIN
    DROP DATABASE VENTAS
END

CREATE DATABASE VENTAS
ON(
NAME='VENTAS_DATA',
FILENAME='C:\Users\joel_\Desktop\database\VENTAS_DATA.MDF',
SIZE=5MB,
MAXSIZE=15MB,
FILEGROWTH=50%
)
LOG ON(
NAME='VENTAS_LOG',
FILENAME='C:\Users\joel_\Desktop\database\VENTAS_LOG.LDF',
SIZE=5MB,
MAXSIZE=15MB,
FILEGROWTH=2MB
);
GO


USE VENTAS
GO

CREATE TABLE DEPARTAMENTO(
 NRO_DEPTO NUMERIC(4) CONSTRAINT PK_DEPT PRIMARY KEY,
 NOMBRE_DEPTO  VARCHAR(20),
 LOCAL    VARCHAR(20))
go

CREATE TABLE EMPLEADO(
 NRO_EMPL     NUMERIC(4) CONSTRAINT PK_EMP PRIMARY KEY,
 NOMBRE_EMPL     VARCHAR(20),
 TRABAJO       VARCHAR(15),
 COD_TARJ       NUMERIC(4),
 FECH_CONT  DATETIME,
 SALARIO       DECIMAL(7,2),
 COMISION      DECIMAL(7,2),
 NRO_DEPTO    NUMERIC(4) )
CREATE TABLE CLIENTE(
 IDCLIENTE      NUMERIC(6),
 NOMBRE       CHAR(45),
 DIRECCION     CHAR(40),
 CIUDAD       CHAR(30),
 ESTADO       CHAR(2),
 AREA        NUMERIC(3),
 TELEFONO      CHAR(9),
 REPID       NUMERIC(4),
 CREDITO_LIMITITADO NUMERIC(9,2),
 COMENTARIOS    VARCHAR(2000)
 CONSTRAINT CLIENTE_PRIMARY PRIMARY KEY(IDCLIENTE))

 go
 ALTER TABLE EMPLEADO ADD CONSTRAINT FK_DEPARTAMENTO_EMPLEADO FOREIGN KEY(NRO_DEPTO)
 REFERENCES DEPARTAMENTO(NRO_DEPTO)
ALTER TABLE EMPLEADO ADD CONSTRAINT FK_EMPLEADO_EMPLEADO FOREIGN KEY(COD_TARJ)
 REFERENCES EMPLEADO(NRO_EMPL)

 GO
  GO
CREATE TABLE ORDEN(
 ID_ORDEN      NUMERIC(4) NOT NULL,
 FECHA_ORDEN  DATETIME,
 COMISION_PLAN   CHAR(1),
IDCLIENTE    NUMERIC(6) NOT NULL, 
 FECHA_ENVIO  DATETIME,
 TOTAL      DECIMAL(8,2) CONSTRAINT TOTAL_ZERO CHECK (TOTAL>=0),
 NRO_EMPL      NUMERIC(4)  CONSTRAINT FK_NRO_EMPL REFERENCES EMPLEADO,  
 CONSTRAINT ORDEN_FOREIGN_KEY FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
 CONSTRAINT ORDEN_PRIMARY_KEY PRIMARY KEY (ID_ORDEN))
CREATE TABLE PRODUCTO(
 IDPRODUC      NUMERIC(6) CONSTRAINT PRODUCTO_PRIMARY_KEY PRIMARY KEY,
 DESCRIPCION      CHAR(30)
 )
 
go


CREATE TABLE CATEGORIA(
 ORDCAT        NUMERIC(4) NOT NULL,
 NRO_CAT      NUMERIC(4) NOT NULL,
 IDPRODUC      NUMERIC(6),
 PRECIO_ACTUAL  DECIMAL(8,2),
 CANTIDAD     DECIMAL(8),
 TOTAL_CAT      DECIMAL(8,2),
 CONSTRAINT CATEGORIA_FOREIGN_KEY FOREIGN KEY(ORDCAT) REFERENCES ORDEN(iD_ORDEN ),
 CONSTRAINT CATEGORIA_FK_PRODUCTO FOREIGN KEY( IDPRODUC) REFERENCES PRODUCTO( IDPRODUC ),
 CONSTRAINT CATEGORIA_PRIMARY_KEY PRIMARY KEY(ORDCAT ,IDPRODUC ))
go