USE MASTER;
GO

CREATE DATABASE RESPALDO_1 ON
(
    NAME=[VENTAS],
    FILENAME='C:\Users\joel_\Desktop\database'
)  AS SNAPSHOT OF [VENTAS];

USE VENTAS
SELECT * FROM DEPARTAMENTO
INSERT INTO DEPARTAMENTO VALUES(40, 'OPERACIONES', 'LIMA')
INSERT INTO DEPARTAMENTO VALUES(50, 'SISTEMAS', 'CALLAO')


SELECT * FROM CLIENTE

UPDATE CLIENTE SET NOMBRE = 'JACKSPORT' WHERE IDCLIENTE = 100

USE REPALDO_1
USE MASTER

RESTORE DATABASE [VENTAS] FROM DATABASE_SNAPSHOT = 'RESPALDO_1'
GO

DROP DATABASE RESPALDO_1;
GO
