USE MASTER;
GO

--LISTA LA BASE DE DATOS CREADAS
SELECT name, physical_name FROM sys.master_files WHERE database_id = DB_ID('VENTAS');

--CREA EL SNAPSHOT
-- RECUERDA USAR EL NOMBRE DEL ARCHIVO Y NO EL NOMBRE DE LA BASE DE DATOS PARA CREAR EL SNAPSHOT

CREATE DATABASE RESPALDO1 ON 
(
    NAME = 'VENTAS_DATA', --NOMBRE DEL ARCHIVO
    FILENAME = 'C:\database\VENTAS_DATA.ss'
)
AS SNAPSHOT OF VENTAS; --NOMBRE DE LA BASE DE DATOS


--HACIENDO CAMBIOS EN LA BASE DE DATOS VENTAS
USE VENTAS
SELECT * FROM DEPARTAMENTO
INSERT INTO DEPARTAMENTO VALUES(40, 'OPERACIONES', 'LIMA')
INSERT INTO DEPARTAMENTO VALUES(50, 'SISTEMAS', 'CALLAO')


SELECT * FROM CLIENTE

UPDATE CLIENTE SET NOMBRE = 'JACKSPORT' WHERE IDCLIENTE = 100


--USAR EL SNAPSHOT
USE RESPALDO1
USE MASTER

--HACER QUE LOS DATOS SE RESTAUREN COMO EN EL SNAPSHOT
-- RECUERDA QUE DEBES HACER UN DROP CONNECTION EN:
-- BASE DE DATOS >> TASKS >> DETACH >> 	CHECK ON DROP AND UPDATE STATISTIC
RESTORE DATABASE [VENTAS] FROM DATABASE_SNAPSHOT = 'RESPALDO1'
GO

--DELETE EL SNAPSHOT
DROP DATABASE RESPALDO1;
GO
