
--PARA CERAR UN NUEVO USUARIO DEBE ESTAR EN MASTER
-- RECUERDA QUE EL QUERY DEBE SER CREADO DESDE EL SERVER PRINCIPAL Y NO DESDE UN USUARIO
USE MASTER
GO

--CREAREMOS UN NUEVO USUARIO
CREATE LOGIN UNISISTEMAS WITH PASSWORD='123456'