------CREACION DE LA BD BIBLIOTECA-------------

CREATE DATABASE BIBLIOTECA
GO

USE BIBLIOTECA
GO


CREATE TABLE DISTRITOS
(COD_DIS CHAR(4)NOT NULL PRIMARY KEY CHECK(COD_DIS LIKE'D[0-9][0-9][0-9]'),
NOM_DIS VARCHAR(30)NOT NULL UNIQUE,
DES_DIS VARCHAR(50)NULL)
GO

CREATE TABLE TIPOS
(COD_TIP CHAR(4)NOT NULL PRIMARY KEY CHECK(COD_TIP LIKE'T[0-9][0-9][0-9]'),
NOM_TIP VARCHAR(30)NOT NULL UNIQUE,
DES_TIP VARCHAR(50)NULL)
GO
CREATE TABLE LECTORES
(COD_LEC CHAR(4)NOT NULL PRIMARY KEY CHECK(COD_LEC LIKE'L[0-9][0-9][0-9]'),
NOM_LEC VARCHAR(30)NOT NULL UNIQUE,
DIR_LEC VARCHAR(50)NOT NULL,
DIS_LEC CHAR(4)NOT NULL FOREIGN KEY(DIS_LEC)REFERENCES DISTRITOS,
TIP_LEC CHAR(4)NOT NULL FOREIGN KEY(TIP_LEC)REFERENCES TIPOS,
FRE_LEC DATETIME DEFAULT(GETDATE())NOT NULL,
EST_LEC BIT DEFAULT(1)NOT NULL,
TEL_LEC CHAR(8) NULL CHECK(TEL_LEC LIKE'[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
OBS_LEC VARCHAR(50) NULL)
GO
CREATE TABLE CARGOS
(COD_CAR CHAR(4)NOT NULL PRIMARY KEY CHECK(COD_CAR LIKE'C[0-9][0-9][0-9]'),
NOM_CAR VARCHAR(30)NOT NULL UNIQUE,
DES_CAR VARCHAR(50)NULL)
GO
CREATE TABLE PERSONAL
(COD_PER CHAR(4)NOT NULL PRIMARY KEY CHECK(COD_PER LIKE'P[0-9][0-9][0-9]'),
NOM_PER VARCHAR(30)NOT NULL UNIQUE,
DIR_PER VARCHAR(50)NOT NULL,
DIS_PER CHAR(4)NOT NULL FOREIGN KEY (DIS_PER) REFERENCES DISTRITOS,
CAR_PER CHAR(4)NOT NULL FOREIGN KEY (CAR_PER) REFERENCES CARGOS,
FRE_PER DATETIME DEFAULT(GETDATE())NOT NULL,
EST_PER BIT DEFAULT(1)NOT NULL,
TEL_PER VARCHAR(8) NULL CHEck(TEL_PER LIKE'[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
OBS_PER VARCHAR(50) NULL)
GO
CREATE TABLE CATEGORIAS
(COD_CAT CHAR(4) NOT NULL PRIMARY KEY CHECK(COD_CAT LIKE 'K[0-9][0-9][0-9]'),
NOM_CAT VARCHAR(30) NOT NULL UNIQUE,
DES_CAT VARCHAR(50)NULL)
GO
CREATE TABLE AUTORES
(COD_AUT CHAR(4) NOT NULL PRIMARY KEY CHECK(COD_AUT LIKE 'A[0-9][0-9][0-9]'),
NOM_AUT VARCHAR(30) NOT NULL UNIQUE,
DES_AUT VARCHAR(50)NULL)
GO
CREATE TABLE UBICACION
(COD_UBI CHAR(4) NOT NULL PRIMARY KEY CHECK(COD_UBI LIKE 'U[0-9][0-9][0-9]'),
NOM_UBI VARCHAR(30) NOT NULL UNIQUE,
DES_UBI VARCHAR(50)NULL)
GO
CREATE TABLE LIBROS
(COD_LIB CHAR(4)NOT NULL PRIMARY KEY CHECK(COD_LIB LIKE'L[0-9][0-9][0-9]'),
NOM_LIB VARCHAR(30)NOT NULL UNIQUE,
CAT_LIB CHAR(4)NOT NULL FOREIGN KEY (CAT_LIB)REFERENCES CATEGORIAS,
FIN_LIB DATETIME DEFAULT(GETDATE())NOT NULL,
AUT_LIB CHAR(4)NOT NULL FOREIGN KEY (AUT_LIB)REFERENCES AUTORES,
FPU_LIB DATETIME NOT NULL,
UBI_LIB CHAR(4)NOT NULL FOREIGN KEY (UBI_LIB)REFERENCES UBICACION,
EST_LIB BIT DEFAULT(1)NOT NULL,
CON_LIB BIT DEFAULT(1) NULL,
OBS_LIB VARCHAR(50) NULL)
GO
CREATE TABLE PRESTAMOS
(NRO_PRE CHAR(4)NOT NULL PRIMARY KEY CHECK(NRO_PRE LIKE'N[0-9][0-9][0-9]'),
FRE_PRE DATETIME DEFAULT(GETDATE())NOT NULL,
LEC_PRE CHAR(4)NOT NULL FOREIGN KEY (LEC_PRE)REFERENCES LECTORES,
PER_PRE CHAR(4)NOT NULL FOREIGN KEY(PER_PRE)REFERENCES PERSONAL,
LIB_PER CHAR(4)NOT NULL FOREIGN KEY(LIB_PER)REFERENCES LIBROS,
CON_PRE BIT DEFAULT(1)NOT NULL,
FDE_PRE DATETIME NOT NULL,
EST_PRE BIT DEFAULT(1)NOT NULL,
OBS_PRE VARCHAR(50) NULL)