
-- AGREGAR COMO ADMINISTRADOR AL USUARIO UNISISTEMAS
SP_ADDUSER [UNISISTEMAS], ADMINISTRADOR
GO


--CONCEDER PERMISOS PARA EL USUARIO SISTEMASUNI PARA TODOS LOS COMANDOS DML A LAS TABLAS 
-- DE LA BD BIBLIOTECA

--TENER EN CUENTA QUE ACA SOLO SE ESTA DANDO PERMISOS DE SELECT

GRANT SELECT ON AUTORES TO Administrador
GRANT SELECT ON CARGOS TO Administrador
GRANT SELECT ON CATEGORIAS TO Administrador
GRANT SELECT ON DISTRITOS TO Administrador
GRANT SELECT ON LECTORES TO Administrador
GRANT SELECT ON LIBROS TO Administrador
GRANT SELECT ON PERSONAL TO Administrador
GRANT SELECT ON PRESTAMOS TO Administrador
GRANT SELECT ON TIPOS TO Administrador
GRANT SELECT ON UBICACION TO Administrador

GO

--DAR OTROS PERMISOS COMO INSERT, UPDATE AND DELETE
GRANT INSERT,UPDATE,DELETE ON AUTORES TO Administrador
GRANT INSERT,UPDATE,DELETE ON CARGOS TO Administrador
GRANT INSERT,UPDATE,DELETE ON CATEGORIAS TO Administrador
GRANT INSERT,UPDATE,DELETE ON DISTRITOS TO Administrador
GRANT INSERT,UPDATE,DELETE ON LECTORES TO Administrador
GRANT INSERT,UPDATE,DELETE ON LIBROS TO Administrador
GRANT INSERT,UPDATE,DELETE ON PERSONAL TO Administrador
GRANT INSERT,UPDATE,DELETE ON PRESTAMOS TO Administrador
GRANT INSERT,UPDATE,DELETE ON TIPOS TO Administrador
GRANT INSERT,UPDATE,DELETE ON UBICACION TO Administrador

