/*==============================================================*/
-- CREAR LA BASE DE DATOS Y LOS REGISTROS EN FISICO
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'ECORP')
BEGIN
    DROP DATABASE ESCUELA
END

CREATE DATABASE ECORP
ON(
NAME='ECORP_DATA',
FILENAME='C:\database\ECORP_DATA.MDF',
SIZE=5MB,
MAXSIZE=15MB,
FILEGROWTH=50%
)
LOG ON(
NAME='ECORP_LOG',
FILENAME='C:\database\ECORP_LOG.LDF',
SIZE=5MB,
MAXSIZE=15MB,
FILEGROWTH=2MB
);
GO