/*==============================================================*/
--USAR LA BASE DE DATOS
USE ECORP
GO

-- CREAR LOS SCHEMAS
CREATE SCHEMA PROVEEDORES;
GO
CREATE SCHEMA INVENTARIO;
GO
CREATE SCHEMA OPERACIONES;
GO
CREATE SCHEMA VENTAS;
GO